const {app,BrowserWindow,dialog,ipcMain,shell}=require('electron');
const fs=require('fs'),path=require('path'),os=require('os'),XLSX=require('xlsx');
const {spawn}=require('child_process');
let win;
const runtimeRoot=()=>app.isPackaged?path.join(process.resourcesPath,'analysis-runtime'):path.join(__dirname,'../analysis-runtime');
function create(){win=new BrowserWindow({width:1440,height:900,minWidth:1100,minHeight:720,backgroundColor:'#f4f6f8',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false}});win.loadURL(app.isPackaged?`file://${path.join(__dirname,'../dist/index.html')}`:'http://127.0.0.1:5174')}
ipcMain.handle('project:save',async(_,project)=>{const r=await dialog.showSaveDialog({defaultPath:`${safe(project.meta?.name||'TSR_Project')}.tsr.json`,filters:[{name:'TSR Studio Project',extensions:['json']}]});if(r.canceled||!r.filePath)return null;fs.writeFileSync(r.filePath,JSON.stringify(project,null,2));return r.filePath});
ipcMain.handle('project:open',async()=>{const r=await dialog.showOpenDialog({properties:['openFile'],filters:[{name:'TSR Studio Project',extensions:['json']}]});if(r.canceled||!r.filePaths[0])return null;return JSON.parse(fs.readFileSync(r.filePaths[0],'utf8'))});
ipcMain.handle('file:read',async(_,kind)=>{const r=await dialog.showOpenDialog({properties:['openFile'],filters:[{name:kind||'Data',extensions:['xlsx','xls','csv','tsv']}]});if(r.canceled||!r.filePaths[0])return null;return {name:path.basename(r.filePaths[0]),bytes:fs.readFileSync(r.filePaths[0]).toString('base64')}});
ipcMain.handle('analysis:python',async(_,payload)=>runJsonProcess(path.join(runtimeRoot(),'python/runner.py'),payload));
ipcMain.handle('analysis:deseq2',async(_,payload)=>runDESeq2(payload));
ipcMain.handle('analysis:limma',async(_,payload)=>runLimma(payload));
ipcMain.handle('analysis:deep-python',async(_,payload)=>runJsonProcess(path.join(runtimeRoot(),'python/deep_runner.py'),payload));
ipcMain.handle('analysis:deep-r',async(_,payload)=>runDeepR(payload));
ipcMain.handle('runtime:check',async()=>({platform:process.platform,architecture:process.arch,python:await probePython(),r:await probeR(),rPackages:await inspectRPackages(),docking:await probe(['vina','--version']),md:await probe(['gmx','--version'])}));
ipcMain.handle('runtime:r-packages',async()=>inspectRPackages());
ipcMain.handle('runtime:install-r-packages',async(_,packages)=>installRPackages(Array.isArray(packages)?packages:[]));
ipcMain.handle('runtime:install-r',async()=>{
 if(process.platform!=='darwin')return {ok:false,error:'当前一键安装器仅适用于macOS'};
 const installer=path.join(process.resourcesPath,'Install_TSR_R_Runtime_macOS.command');
 if(!fs.existsSync(installer))return {ok:false,error:`安装器缺失：${installer}`};
 try{fs.chmodSync(installer,0o755)}catch{}
 const error=await shell.openPath(installer);
 return error?{ok:false,error}:{ok:true};
});
ipcMain.handle('structure:select',async(_,kind)=>{const ext=kind==='trajectory'?['xtc','trr']:kind==='topology'?['tpr','gro','pdb']:['pdbqt'];const r=await dialog.showOpenDialog({properties:['openFile'],filters:[{name:String(kind),extensions:ext}]});return r.canceled?null:r.filePaths[0]});
ipcMain.handle('docking:run',async(_,payload)=>runDocking(payload));
ipcMain.handle('md:analyze',async(_,payload)=>runMDAnalysis(payload));
ipcMain.handle('md:run',async(_,payload)=>runMDProduction(payload));
ipcMain.handle('compound:resolve',async(_,payload)=>resolveCompound(payload));
ipcMain.handle('disease:targets',async(_,disease)=>resolveDiseaseTargets(disease));
function pythonCandidates(){const rr=runtimeRoot(),list=[];if(process.platform==='darwin'){const bin=path.join(rr,'Python/bin/python3');if(fs.existsSync(bin))list.push({bin,env:{PYTHONPATH:path.join(rr,'python-packages')},bundled:true});for(const bin of['/opt/homebrew/bin/python3','/usr/local/bin/python3','/usr/bin/python3'])if(fs.existsSync(bin))list.push({bin,env:{},bundled:false})}if(process.platform==='win32'){const bin=path.join(rr,'Python/python.exe');if(fs.existsSync(bin))list.push({bin,env:{PYTHONPATH:path.join(rr,'python-packages')},bundled:true})}for(const bin of(process.platform==='win32'?['python','py']:['python3','python']))list.push({bin,env:{},bundled:false});return uniqueCandidates(list)}
function runJsonProcess(script,payload){return new Promise(resolve=>{const commands=pythonCandidates(),logs=[];let idx=0;const attempt=()=>{if(idx>=commands.length)return resolve({ok:false,error:'未找到Python分析运行时或科学计算依赖',logs});const c=commands[idx++],p=spawn(c.bin,[script],{stdio:['pipe','pipe','pipe'],env:{...process.env,...c.env}});let out='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>logs.push(String(d).trim()));p.on('error',attempt);p.on('close',code=>{if(code!==0)return /not found|ENOENT/i.test(logs.join(' '))?attempt():resolve({ok:false,error:logs.join('\n')||`Python退出码${code}`,logs});try{resolve({...JSON.parse(out),logs})}catch{resolve({ok:false,error:'Python返回结果无法解析',logs:[...logs,out]})}});p.stdin.end(JSON.stringify(payload))};attempt()})}
function runDESeq2(payload){return new Promise(resolve=>{const logs=[],asset=payload.asset||{},samples=(payload.samples||[]).filter(s=>s.included!==false),meta=payload.meta||{},data=asset.data||[];if(!data.length)return resolve({ok:false,error:'转录组数据为空',logs});const smap=new Map(samples.map(s=>[s.id,s])),sampleCols=Object.keys(data[0]).filter(c=>smap.has(c)),idCol=['Gene_ID','gene_id','Gene','ID','id','Name'].find(c=>c in data[0])||Object.keys(data[0])[0];if(sampleCols.length<4)return resolve({ok:false,error:'DESeq2可匹配样本少于4个',logs});if(data.some(r=>sampleCols.some(c=>{const v=Number(r[c]);return !Number.isFinite(v)||v<0||!Number.isInteger(v)})))return resolve({ok:false,error:'DESeq2要求非负整数raw counts；TPM/FPKM不能进入该流程',logs});
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tsr-deseq2-')),counts=path.join(dir,'counts.csv'),design=path.join(dir,'samples.csv'),output=path.join(dir,'result.csv'),script=path.join(runtimeRoot(),'r/deseq2_runner.R');
 const countRows=data.map(r=>Object.fromEntries([['Feature_ID',r[idCol]],...sampleCols.map(c=>[c,r[c]])]));
 fs.writeFileSync(counts,XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(countRows)));
 const designRows=sampleCols.map(id=>{const s=smap.get(id);return {Sample_ID:id,group:s.group,batch:s.batch||'',sex:s.sex||'',tissue:s.tissue||'',timepoint:s.timepoint||'',animalId:s.animalId||id}});
 fs.writeFileSync(design,XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(designRows)));
 const commands=rCandidates();let idx=0;const finish=x=>{try{fs.rmSync(dir,{recursive:true,force:true})}catch{}resolve(x)},attempt=()=>{if(idx>=commands.length)return finish({ok:false,error:'未找到可用的R 4.3+与DESeq2运行时',logs});const command=commands[idx++],analysisArgs=[counts,design,output,meta.controlGroup,meta.modelGroup,(meta.treatmentGroups||[]).join(',')],rArgs=[...command.prefix,script,...analysisArgs],p=spawn(command.bin,rArgs,{env:{...process.env,...command.env}});p.stderr.on('data',d=>logs.push(String(d).trim()));p.on('error',attempt);p.on('close',code=>{if(code!==0){const msg=logs.join('\n');return /not found|ENOENT/i.test(msg)?attempt():finish({ok:false,error:msg||`R退出码${code}`,logs})}try{const wb=XLSX.readFile(output),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:null}),rawById=new Map(data.map(r=>[String(r[idCol]),r]));for(const r of rows){const raw=rawById.get(String(r.featureId));r.label=String(raw?.Gene||raw?.Name||r.featureId)}finish({ok:true,result:{engine:'R DESeq2 0.6.3',module:'transcriptomics',status:'completed',parameters:{model:'DESeq2 negative binomial GLM',design:'~ group',lowCountFilter:'count>=10 in at least max(2,25% samples)'},qc:{inputFeatures:data.length,matchedSamples:sampleCols.length},summaries:[],differential:rows,pca:[],messages:[]},logs})}catch(e){finish({ok:false,error:`DESeq2结果读取失败：${e.message}`,logs})}})};attempt()})}
function runLimma(payload){return runRMatrix(payload,'limma_proteomics_runner.R','R limma 1.0.1','proteomics')}
function runDeepR(payload){return new Promise(resolve=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tsr-deep-r-')),input=path.join(dir,'input.json'),output=path.join(dir,'output.json'),script=path.join(runtimeRoot(),'r/deep_analysis_runner.R'),logs=[];fs.writeFileSync(input,JSON.stringify(payload));const commands=rCandidates();let i=0;const finish=x=>{try{fs.rmSync(dir,{recursive:true,force:true})}catch{}resolve(x)},attempt=()=>{if(i>=commands.length)return finish({ok:false,error:'未找到R高级分析运行时',logs});const c=commands[i++],p=spawn(c.bin,[...c.prefix,script,input,output],{env:{...process.env,...c.env}});p.stderr.on('data',d=>logs.push(String(d).trim()));p.on('error',attempt);p.on('close',code=>{if(code!==0)return finish({ok:false,error:logs.join('\n')||`R退出码${code}`,logs});try{finish({ok:true,result:JSON.parse(fs.readFileSync(output,'utf8')),logs})}catch(e){finish({ok:false,error:`R高级分析结果读取失败：${e.message}`,logs})}})};attempt()})}
function runRMatrix(payload,scriptName,engine,module){return new Promise(resolve=>{const logs=[],asset=payload.asset||{},samples=(payload.samples||[]).filter(s=>s.included!==false),meta=payload.meta||{},data=asset.data||[];if(!data.length)return resolve({ok:false,error:`${module}数据为空`,logs});const smap=new Map(samples.map(s=>[s.id,s])),sampleCols=Object.keys(data[0]).filter(c=>smap.has(c)),idCol=['Protein_ID','Gene_ID','Protein','Gene','Feature_ID','ID','Name'].find(c=>c in data[0])||Object.keys(data[0])[0];if(sampleCols.length<4)return resolve({ok:false,error:'可匹配样本少于4个',logs});const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tsr-r-')),matrix=path.join(dir,'matrix.csv'),design=path.join(dir,'samples.csv'),output=path.join(dir,'result.csv'),script=path.join(runtimeRoot(),'r',scriptName),rows=data.map(r=>Object.fromEntries([['Feature_ID',r[idCol]],...sampleCols.map(c=>[c,r[c]])]));fs.writeFileSync(matrix,XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(rows)));const designRows=sampleCols.map(id=>{const s=smap.get(id);return {Sample_ID:id,group:s.group,batch:s.batch||'',sex:s.sex||'',tissue:s.tissue||'',timepoint:s.timepoint||'',animalId:s.animalId||id}});fs.writeFileSync(design,XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(designRows)));const covariates=['batch','sex','tissue','timepoint'].filter(k=>new Set(designRows.map(x=>x[k]).filter(Boolean)).size>1),commands=rCandidates();let i=0,finish=x=>{try{fs.rmSync(dir,{recursive:true,force:true})}catch{}resolve(x)},attempt=()=>{if(i>=commands.length)return finish({ok:false,error:'未找到可用R运行时或正式统计依赖',logs});const c=commands[i++],a=[matrix,design,output,meta.controlGroup,meta.modelGroup,(meta.treatmentGroups||[]).join(',')],ra=[...c.prefix,script,...a],p=spawn(c.bin,ra,{env:{...process.env,...c.env}});p.stderr.on('data',d=>logs.push(String(d).trim()));p.on('error',attempt);p.on('close',code=>{if(code!==0)return finish({ok:false,error:logs.join('\n')||`R退出码${code}`,logs});try{const wb=XLSX.readFile(output),differential=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:null});finish({ok:true,result:{engine,module,status:'completed',parameters:{model:'limma empirical Bayes',design:`~0 + group${covariates.map(x=>` + ${x}`).join('')}`,covariates,robust:true,trend:true,missingFilter:'feature missing <=50%'},qc:{inputFeatures:data.length,analyzedFeatures:new Set(differential.map(x=>x.featureId)).size,matchedSamples:sampleCols.length,covariates},summaries:[],differential,pca:[],messages:[]},logs})}catch(e){finish({ok:false,error:`limma结果读取失败：${e.message}`,logs})}})};attempt()})}
function rUserLibrary(){const p=path.join(app.getPath('userData'),'R-library');try{fs.mkdirSync(p,{recursive:true})}catch{}return p}
function rCandidates(){const rr=runtimeRoot(),list=[],userLib=rUserLibrary(),baseEnv={R_LIBS_USER:userLib};if(process.platform==='darwin'){const home=path.join(rr,'R'),bin=path.join(home,'bin','Rscript');if(fs.existsSync(bin))list.push({bin,prefix:[],env:{...baseEnv,R_HOME:home,DYLD_FALLBACK_LIBRARY_PATH:path.join(home,'lib')},bundled:true});for(const bin of['/Library/Frameworks/R.framework/Resources/bin/Rscript','/opt/homebrew/bin/Rscript','/usr/local/bin/Rscript'])if(fs.existsSync(bin))list.push({bin,prefix:[],env:baseEnv,bundled:false})}if(process.platform==='win32'){const home=path.join(rr,'R'),bin=path.join(home,'bin','Rscript.exe');if(fs.existsSync(bin))list.push({bin,prefix:[],env:{...baseEnv,R_HOME:home},bundled:true});for(const home of windowsRHomes())list.push({bin:path.join(home,'bin','Rscript.exe'),prefix:[],env:{...baseEnv,R_HOME:home},bundled:false})}for(const bin of(process.platform==='win32'?['Rscript.exe','Rscript']:['Rscript']))list.push({bin,prefix:[],env:baseEnv,bundled:false});return uniqueCandidates(list)}
function windowsRHomes(){if(process.platform!=='win32')return[];const roots=[process.env.ProgramFiles&&path.join(process.env.ProgramFiles,'R'),process.env.LOCALAPPDATA&&path.join(process.env.LOCALAPPDATA,'Programs','R')].filter(Boolean),homes=[];for(const root of roots)try{for(const name of fs.readdirSync(root))if(/^R-\d/i.test(name))homes.push(path.join(root,name))}catch{}return homes.sort().reverse()}
function uniqueCandidates(list){const seen=new Set();return list.filter(x=>{const key=x.bin;return seen.has(key)?false:(seen.add(key),true)})}
async function probeR(){const attempts=[];for(const c of rCandidates()){const expr='core<-c("DESeq2","limma","edgeR");advanced<-c("jsonlite","WGCNA","clusterProfiler","org.Mm.eg.db","org.Rn.eg.db","org.Hs.eg.db");integrative<-c("MOFA2","mixOmics");a<-vapply(core,requireNamespace,logical(1),quietly=TRUE);b<-vapply(advanced,requireNamespace,logical(1),quietly=TRUE);d<-vapply(integrative,requireNamespace,logical(1),quietly=TRUE);cat(R.version.string,"| core:",paste(names(a),a,sep="=",collapse=","),"| deep:",paste(names(b),b,sep="=",collapse=","),"| integrative:",paste(names(d),d,sep="=",collapse=","));quit(status=if(all(a))0 else 3)',r=await probe([c.bin,...c.prefix,'-e',expr],c.env);attempts.push({path:c.bin,found:r.found,output:r.version});if(r.available)return {...r,path:c.bin,bundled:!!c.bundled,dependencies:true,advancedDependencies:!/=FALSE/.test((r.version.split('| deep:')[1]||'')),integrativeDependencies:!/=FALSE/.test((r.version.split('| integrative:')[1]||'')),attempts}}const found=attempts.find(x=>x.found);return {available:false,version:found?'已找到R，但缺少DESeq2/limma/edgeR':'未找到R；macOS请安装官方R后重新检测',path:found?.path||'',bundled:false,dependencies:false,advancedDependencies:false,integrativeDependencies:false,attempts}}
async function probePython(){const attempts=[];for(const c of pythonCandidates()){const code='import json,pandas,scipy,sklearn,importlib.util; print(json.dumps({"core":True,"shap":importlib.util.find_spec("shap") is not None,"xgboost":importlib.util.find_spec("xgboost") is not None}))',r=await probe([c.bin,'-c',code],c.env);attempts.push({path:c.bin,found:r.found,output:r.version});if(r.available){let optional={shap:false,xgboost:false};try{optional=JSON.parse(r.version)}catch{}return {...r,version:`Python scientific stack OK | SHAP=${optional.shap} | XGBoost=${optional.xgboost}`,path:c.bin,bundled:!!c.bundled,advancedDependencies:optional,attempts}}}const found=attempts.find(x=>x.found);return {available:false,version:found?'已找到Python，但缺少pandas/scipy/scikit-learn':'未找到Python',path:found?.path||'',bundled:false,advancedDependencies:{shap:false,xgboost:false},attempts}}
function runRDependencyManager(mode,packages=[]){return new Promise(resolve=>{const script=path.join(runtimeRoot(),'r','dependency_manager.R'),commands=rCandidates(),logs=[];let i=0;const attempt=()=>{if(i>=commands.length)return resolve({ok:false,error:'未找到可用R运行时。请先安装R 4.3或更高版本。',logs});const c=commands[i++],args=[...c.prefix,script,mode,packages.join(',')],p=spawn(c.bin,args,{env:{...process.env,...c.env},windowsHide:true});let out='';p.stdout.on('data',d=>out+=String(d));p.stderr.on('data',d=>logs.push(String(d).trim()));p.on('error',attempt);p.on('close',code=>{const candidates=[out.trim(),...out.trim().split(/\r?\n/).reverse()];let parsed=null;for(const x of candidates)try{parsed=JSON.parse(x);break}catch{}if(parsed)return resolve({...parsed,logs,rPath:c.bin,userLibrary:c.env.R_LIBS_USER});if(code!==0)return resolve({ok:false,error:logs.join('\n')||`R依赖管理器退出码${code}`,logs,rPath:c.bin});resolve({ok:false,error:'R依赖管理器未返回有效结果',logs:[...logs,out]})})};attempt()})}
const inspectRPackages=()=>runRDependencyManager('status');
const installRPackages=packages=>runRDependencyManager('install',packages);
function probe(args,env={}){return new Promise(resolve=>{const p=spawn(args[0],args.slice(1),{env:{...process.env,...env}});let out='',settled=false;const done=x=>{if(settled)return;settled=true;resolve(x)};p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>out+=d);p.on('error',e=>done({available:false,found:false,version:e.message}));p.on('close',c=>done({available:c===0,found:true,version:out.trim().split('\n')[0]}))})}
async function runDocking(x){const receptor=String(x.receptor||''),ligand=String(x.ligand||'');if(!fs.existsSync(receptor)||!fs.existsSync(ligand))return {ok:false,error:'受体或配体文件不存在',logs:[]};if(path.extname(receptor).toLowerCase()!=='.pdbqt'||path.extname(ligand).toLowerCase()!=='.pdbqt')return {ok:false,error:'Vina要求受体和配体均为PDBQT',logs:[]};const nums=['centerX','centerY','centerZ','sizeX','sizeY','sizeZ','exhaustiveness','numModes','seed'];for(const k of nums)if(!Number.isFinite(Number(x[k])))return {ok:false,error:`参数${k}不是有效数字`,logs:[]};const save=await dialog.showSaveDialog({defaultPath:`${safe(x.compoundId||'ligand')}_${safe(x.targetId||'target')}_vina_out.pdbqt`,filters:[{name:'PDBQT pose',extensions:['pdbqt']}]});if(save.canceled||!save.filePath)return {ok:false,error:'用户取消输出位置',logs:[]};const args=['--receptor',receptor,'--ligand',ligand,'--center_x',String(x.centerX),'--center_y',String(x.centerY),'--center_z',String(x.centerZ),'--size_x',String(x.sizeX),'--size_y',String(x.sizeY),'--size_z',String(x.sizeZ),'--exhaustiveness',String(Math.max(1,Math.round(x.exhaustiveness))),'--num_modes',String(Math.max(1,Math.round(x.numModes))),'--seed',String(Math.round(x.seed)),'--out',save.filePath],r=await spawnCapture('vina',args);if(!r.ok)return {...r,error:r.error||'AutoDock Vina运行失败'};const scores=[];for(const line of r.stdout.split(/\r?\n/)){const m=line.match(/^\s*(\d+)\s+(-?\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)/);if(m)scores.push({mode:Number(m[1]),affinity:Number(m[2]),rmsdLower:Number(m[3]),rmsdUpper:Number(m[4])})}return {ok:true,result:{id:`dock-${Date.now()}`,createdAt:new Date().toISOString(),compoundId:String(x.compoundId||''),targetId:String(x.targetId||''),receptor,ligand,engine:'AutoDock Vina',parameters:Object.fromEntries(nums.map(k=>[k,Number(x[k])])),scores,poseFile:save.filePath,log:[r.stdout,r.stderr].filter(Boolean).join('\n'),status:'completed'},logs:r.stderr?[r.stderr]:[]}}
async function runMDAnalysis(x){const topology=String(x.topology||''),trajectory=String(x.trajectory||''),group=Math.max(0,Math.round(Number(x.group??1)));if(!fs.existsSync(topology)||!fs.existsSync(trajectory))return {ok:false,error:'拓扑或轨迹文件不存在',logs:[]};const pick=await dialog.showOpenDialog({title:'选择动力学分析输出目录',properties:['openDirectory','createDirectory']});if(pick.canceled||!pick.filePaths[0])return {ok:false,error:'用户取消输出目录',logs:[]};const outDir=pick.filePaths[0],jobs=[['RMSD','nm','rmsd.xvg',['rms','-s',topology,'-f',trajectory,'-o',path.join(outDir,'rmsd.xvg'),'-tu','ns'],`${group}\n${group}\n`],['RMSF','nm','rmsf.xvg',['rmsf','-s',topology,'-f',trajectory,'-o',path.join(outDir,'rmsf.xvg')],`${group}\n`],['Radius_of_gyration','nm','gyrate.xvg',['gyrate','-s',topology,'-f',trajectory,'-o',path.join(outDir,'gyrate.xvg')],`${group}\n`],['SASA','nm2','sasa.xvg',['sasa','-s',topology,'-f',trajectory,'-o',path.join(outDir,'sasa.xvg')],`${group}\n`],['Hydrogen_bonds','count','hbond.xvg',['hbond','-s',topology,'-f',trajectory,'-num',path.join(outDir,'hbond.xvg')],`${group}\n${group}\n`]],series=[],logs=[];for(const [name,unitY,file,args,input] of jobs){const r=await spawnCapture('gmx',args,input);logs.push(`${name}: ${r.ok?'OK':'FAILED'}\n${r.stderr}`);if(r.ok&&fs.existsSync(file))series.push({name,unitX:name==='RMSF'?'residue':'ns',unitY,points:parseXvg(file),sourceFile:file})}if(!series.length)return {ok:false,error:'GROMACS未生成可解析曲线；请检查选择组编号和轨迹兼容性',logs};return {ok:true,result:{id:`md-${Date.now()}`,createdAt:new Date().toISOString(),compoundId:String(x.compoundId||''),targetId:String(x.targetId||''),engine:'GROMACS',trajectory,topology,series,outputDirectory:outDir,log:logs.join('\n\n'),status:'completed'},logs}}
async function runMDProduction(x){const tpr=String(x.topology||'');if(!fs.existsSync(tpr)||path.extname(tpr).toLowerCase()!=='.tpr')return {ok:false,error:'生产模拟需要已经审查确认的GROMACS TPR文件',logs:[]};const pick=await dialog.showOpenDialog({title:'选择生产期模拟输出目录',properties:['openDirectory','createDirectory']});if(pick.canceled||!pick.filePaths[0])return {ok:false,error:'用户取消输出目录',logs:[]};const dir=pick.filePaths[0],prefix=path.join(dir,safe(x.name||'production')),cpt=`${prefix}.cpt`,resumed=fs.existsSync(cpt),args=['mdrun','-s',tpr,'-deffnm',prefix,'-ntomp',String(Math.max(1,Math.round(Number(x.threads||2))))];if(resumed)args.push('-cpi',cpt,'-append');if(x.gpu===false)args.push('-nb','cpu');const r=await spawnCapture('gmx',args,'',7*24*60*60*1000);return r.ok?{ok:true,result:{topology:tpr,trajectory:`${prefix}.xtc`,checkpoint:cpt,outputDirectory:dir,resumed,log:[r.stdout,r.stderr].join('\n')},logs:r.stderr?[r.stderr]:[]}:{ok:false,error:r.error||'GROMACS生产模拟失败',logs:[r.stderr]}}
function spawnCapture(bin,args,input='',timeoutMs=30*60*1000){return new Promise(resolve=>{let stdout='',stderr='',settled=false;const p=spawn(bin,args,{windowsHide:true});const done=x=>{if(settled)return;settled=true;clearTimeout(timer);resolve(x)};p.stdout.on('data',d=>stdout+=d);p.stderr.on('data',d=>stderr+=d);p.on('error',e=>done({ok:false,stdout,stderr,error:e.message}));p.on('close',code=>done({ok:code===0,stdout,stderr,error:code===0?'':`${bin}退出码${code}`}));if(input)p.stdin.end(input);else p.stdin.end();const timer=setTimeout(()=>{p.kill();done({ok:false,stdout,stderr,error:`${bin}运行超时，已终止`})},timeoutMs)})}
function parseXvg(file){const out=[];for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){if(!line||line[0]==='#'||line[0]==='@')continue;const p=line.trim().split(/\s+/).map(Number);if(p.length>=2&&Number.isFinite(p[0])&&Number.isFinite(p[1]))out.push({x:p[0],y:p[1]})}return out}
async function resolveCompound(x){try{const cid=String(x.pubchemCid||'').trim(),query=cid?`cid/${encodeURIComponent(cid)}`:`name/${encodeURIComponent(String(x.cas||x.name||''))}`,url=`https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/${query}/property/Title,CanonicalSMILES,IsomericSMILES,InChIKey/JSON`,data=await fetchJson(url),p=data?.PropertyTable?.Properties?.[0];if(!p)return {ok:false,error:'PubChem未返回匹配记录'};return {ok:true,result:{name:p.Title||x.name,pubchemCid:String(p.CID||cid),smiles:p.IsomericSMILES||p.ConnectivitySMILES||p.CanonicalSMILES||'',inchiKey:p.InChIKey||'',source:'PubChem PUG REST',queriedAt:new Date().toISOString()}}}catch(e){return {ok:false,error:`PubChem查询失败：${e.message}`}}}
async function resolveDiseaseTargets(disease){try{const endpoint='https://api.platform.opentargets.org/api/v4/graphql',search=await postGraph(endpoint,'query Search($q:String!){search(queryString:$q,entityNames:["disease"],page:{index:0,size:5}){hits{id name entity}}}',{q:String(disease)}),hit=search?.data?.search?.hits?.find(x=>x.entity==='disease')||search?.data?.search?.hits?.[0];if(!hit)return {ok:false,error:'Open Targets未找到疾病实体'};const q='query DiseaseTargets($id:String!){disease(efoId:$id){id name associatedTargets(page:{index:0,size:500}){rows{score target{id approvedSymbol approvedName}}}}}',data=await postGraph(endpoint,q,{id:hit.id}),d=data?.data?.disease,queriedAt=new Date().toISOString(),rows=(d?.associatedTargets?.rows??[]).map(r=>({targetId:r.target.id,symbol:r.target.approvedSymbol,name:r.target.approvedName,associationScore:r.score,source:'Open Targets Platform GraphQL',queriedAt,diseaseId:d.id,diseaseName:d.name}));return {ok:true,result:{disease:{id:d.id,name:d.name},targets:rows,queriedAt}}}catch(e){return {ok:false,error:`Open Targets查询失败：${e.message}`}}}
async function fetchJson(url,options={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),30000);try{const r=await fetch(url,{...options,signal:c.signal,headers:{accept:'application/json',...(options.headers||{})}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
const postGraph=(url,query,variables)=>fetchJson(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,variables})});
const safe=s=>String(s).replace(/[\\/:*?"<>|\s]+/g,'_');
app.whenReady().then(create);app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)create()});
