import {useMemo,useState} from 'react';import * as XLSX from 'xlsx';import {exportDeepFigures} from './deepFigures';import type {DeepAnalysisRun,DeepAnalysisState,DeepMethod,ModuleKey,Project} from './types';
const methodInfo:{id:DeepMethod;name:string;engine:'r'|'python';desc:string}[]=[
 {id:'go',name:'GO富集',engine:'r',desc:'clusterProfiler ORA，输出BP/CC/MF及完整映射率'},
 {id:'kegg',name:'KEGG富集',engine:'r',desc:'clusterProfiler ORA，使用物种背景和BH-FDR'},
 {id:'gsea',name:'GSEA',engine:'r',desc:'基于全量排序列表，不依赖任意差异阈值'},
 {id:'wgcna',name:'WGCNA',engine:'r',desc:'软阈值、模块、模块—性状关联及Hub特征'},
 {id:'correlation',name:'分子—表型关联',engine:'python',desc:'选择行为/生化指标，Spearman与BH-FDR'},
 {id:'machine_learning',name:'机器学习共识筛选',engine:'python',desc:'Elastic Net、随机森林、SVM、交叉验证和置换检验'},
 {id:'overlap',name:'Venn/花瓣/UpSet源数据',engine:'python',desc:'比较不同组学和不同处理的严格显著集合'},
 {id:'multiomics',name:'跨组学相关网络',engine:'python',desc:'共同样本上的跨数据块相关及FDR控制'}];
export function DeepMining({project,save}:{project:Project;save:(state:DeepAnalysisState)=>void}){const [modules,setModules]=useState<ModuleKey[]>(project.deepAnalysis?.selectedModules??project.assets.map(a=>a.module)),[indicators,setIndicators]=useState<string[]>(project.deepAnalysis?.selectedIndicators??[]),[busy,setBusy]=useState(''),[notice,setNotice]=useState('');const runs=project.deepAnalysis?.runs??[],traits=useMemo(()=>{const a=project.assets.find(x=>x.module==='phenotype'),first=a?.data[0]??{};return Object.keys(first).filter(k=>!['Sample_ID','sample_id','Sample','Group','group'].includes(k)&&a?.data.some(r=>Number.isFinite(Number(r[k]))))},[project.assets]);
 const toggle=<T,>(x:T,list:T[],set:(v:T[])=>void)=>set(list.includes(x)?list.filter(v=>v!==x):[...list,x]);
 async function run(m:DeepMethod){if(!window.tsrDesktop)return setNotice('深度分析仅在桌面版调用正式R/Python运行时');const info=methodInfo.find(x=>x.id===m)!;if(!modules.length)return setNotice('请至少选择一个参与分析的组学模块');if(m==='wgcna'&&project.samples.filter(s=>s.included).length<15)return setNotice('WGCNA已阻止：可用独立样本少于15个');setBusy(m);setNotice(`${info.name}正在运行…`);const chosenAssets=project.assets.filter(a=>modules.includes(a.module)),chosenResults=project.results.filter(r=>modules.includes(r.module)),payload={method:m,meta:project.meta,samples:project.samples,assets:chosenAssets,asset:chosenAssets.find(a=>['transcriptomics','proteomics'].includes(a.module)),results:m==='go'||m==='kegg'||m==='gsea'?chosenResults.flatMap(r=>r.differential.map(d=>({...d,module:r.module}))):chosenResults,settings:{modules,indicators,fdr:.05,maxFeatures:300,permutations:100}};const response=info.engine==='r'?await window.tsrDesktop.runDeepR(payload):await window.tsrDesktop.runDeepPython(payload);setBusy('');if(!response.ok||!response.result)return setNotice(`${info.name}未执行：${response.error??'运行时不可用'}。没有生成伪结果。${response.logs?.filter(Boolean).join('；')}`);const result=response.result as DeepAnalysisRun;result.settings=payload.settings;save({selectedModules:modules,selectedIndicators:indicators,runs:[...runs.filter(x=>x.method!==m),result]});setNotice(`${info.name}完成：${Object.values(result.tables).reduce((n,x)=>n+x.length,0)}条结果已保存`) }
 function exportExcel(){const wb=XLSX.utils.book_new();for(const r of runs){XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{方法:r.method,引擎:r.engine,状态:r.status,时间:r.createdAt,...r.summary,参数:JSON.stringify(r.settings),提示:r.messages.join('；')}]),safe(`${r.method}_说明`).slice(0,31));for(const [name,rows] of Object.entries(r.tables))XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),safe(`${r.method}_${name}`).slice(0,31))}XLSX.writeFile(wb,`${safe(project.meta.name)}_TSR_Studio_2.0_Deep_Mining.xlsx`)}
 return <><section><div className="sectionHead"><div><h2>深度生物信息学与机器学习</h2><p>先选择参与筛选的组学和药效指标，再运行对应算法。每项分析均记录参数、运行时、全量结果和限制。</p></div><button disabled={!runs.length} onClick={exportExcel}>导出深度分析Excel</button><button disabled={!runs.length} onClick={()=>exportDeepFigures(project)}>导出深度论文图包</button></div>{notice&&<div className="notice">{notice}</div>}<h3>1. 参与分析的组学</h3><div className="checkGrid">{project.assets.map(a=><label key={a.module}><input type="checkbox" checked={modules.includes(a.module)} onChange={()=>toggle(a.module,modules,setModules)}/>{a.module} · {a.fileName}</label>)}</div><h3>2. 药效/行为指标</h3><p className="muted">未勾选时使用全部数值型表型；勾选后只分析指定指标。</p><div className="checkGrid">{traits.map(x=><label key={x}><input type="checkbox" checked={indicators.includes(x)} onChange={()=>toggle(x,indicators,setIndicators)}/>{x}</label>)}</div></section><section><h2>3. 正式分析方法</h2><div className="methodGrid">{methodInfo.map(m=>{const old=runs.find(x=>x.method===m.id),blocked=m.id==='wgcna'&&project.samples.filter(s=>s.included).length<15;return <article key={m.id}><h3>{m.name}</h3><p>{m.desc}</p><small>{blocked?'阻断：独立样本少于15个':old?`${old.status} · ${old.engine}`:`调用${m.engine==='r'?'R/Bioconductor':'Python/scikit-learn'}`}</small><button disabled={!!busy||blocked} onClick={()=>run(m.id)}>{busy===m.id?'运行中…':old?'重新运行':'运行'}</button></article>})}</div></section>{runs.length>0&&<section><h2>4. 已保存结果</h2><table><thead><tr><th>方法</th><th>状态</th><th>引擎</th><th>结果表</th><th>提示</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td>{methodInfo.find(x=>x.id===r.method)?.name??r.method}</td><td>{r.status}</td><td>{r.engine}</td><td>{Object.entries(r.tables).map(([k,v])=>`${k}:${v.length}`).join('；')}</td><td>{r.messages.join('；')||'—'}</td></tr>)}</tbody></table></section>}</>}
const safe=(s:string)=>String(s).replace(/[^A-Za-z0-9\u4e00-\u9fa5_.-]+/g,'_');
