import type {CompoundCandidate,DiscoveryState,DifferentialRow,EvidenceGrade,Project,TargetCandidate} from './types';

const first=(r:Record<string,unknown>,keys:string[])=>{for(const k of keys){const v=r[k];if(v!==undefined&&v!==null&&String(v).trim())return String(v).trim()}return ''};
const number=(r:Record<string,unknown>,keys:string[])=>{for(const k of keys){const v=Number(r[k]);if(Number.isFinite(v))return v}return undefined};
const clamp=(x:number)=>Math.max(0,Math.min(1,x));
const sig=(fdr:number)=>clamp(-Math.log10(Math.max(fdr,1e-12))/6);

export function buildDiscovery(project:Project):DiscoveryState{
 const priorCompounds=new Map((project.discovery?.compounds??[]).map(x=>[x.name.trim().toUpperCase(),x])),chemistry=project.assets.find(a=>a.module==='chemistry'),compounds:CompoundCandidate[]=(chemistry?.data??[]).map((r,i)=>{
  const name=first(r,['Name','Compound','Compound_Name','化合物','成分名称'])||`Compound_${i+1}`,cas=first(r,['CAS','CAS号','CAS_Number']),pubchemCid=first(r,['PubChem_CID','PubChem CID','CID']),smiles=first(r,['SMILES','Canonical_SMILES','Isomeric_SMILES']),abundance=number(r,['abundance','Abundance','Area','Peak_Area']),exposure=number(r,['exposure','Exposure','Plasma_AUC','Tissue_AUC']),identityLevel=first(r,['identification_level','Identification_Level','MSI_Level'])||'未记录',identity=smiles?1:pubchemCid?.5:cas?.35:0,expo=exposure!==undefined?1:abundance!==undefined?.45:0;
  const prior=priorCompounds.get(name.toUpperCase()),resolvedCas=cas||prior?.cas||'',resolvedCid=pubchemCid||prior?.pubchemCid||'',resolvedSmiles=smiles||prior?.smiles||'',resolvedIdentity=resolvedSmiles?1:resolvedCid?.5:resolvedCas?.35:0;return {id:resolvedCid||resolvedCas||resolvedSmiles||`CHEM:${i+1}`,name,cas:resolvedCas||undefined,pubchemCid:resolvedCid||undefined,smiles:resolvedSmiles||undefined,source:chemistry?.fileName??'',identityLevel:prior?.identityLevel||identityLevel,abundance,exposure,score:100*(.65*resolvedIdentity+.35*expo),flags:[!resolvedCas&&!resolvedCid&&!resolvedSmiles?'缺少CAS/CID/SMILES':'',identityLevel==='未记录'?'身份置信等级未记录':''].filter(Boolean)}
 });
 const grouped=new Map<string,{symbol:string;modules:Set<string>;pairs:{m:DifferentialRow;t:DifferentialRow}[]}>(),model=`${project.meta.modelGroup}_vs_${project.meta.controlGroup}`;
 for(const r of project.results){const base=new Map(r.differential.filter(d=>d.comparison===model).map(d=>[d.featureId,d]));for(const treatment of project.meta.treatmentGroups)for(const t of r.differential.filter(d=>d.comparison===`${treatment}_vs_${project.meta.modelGroup}`)){const m=base.get(t.featureId);if(!m)continue;const key=(t.label||t.featureId).trim().toUpperCase(),x=grouped.get(key)??{symbol:t.label||t.featureId,modules:new Set<string>(),pairs:[]};x.modules.add(r.module);x.pairs.push({m,t});grouped.set(key,x)}}
 const diseaseEvidence=project.discovery?.diseaseEvidence??[],diseaseMap=new Map(diseaseEvidence.map(x=>[x.symbol.trim().toUpperCase(),x]));
 const validatedTargets=new Set([...(project.discovery?.docking??[]).filter(d=>d.scores.some(s=>s.affinity<=-7)).map(d=>d.targetId),...(project.discovery?.md??[]).filter(d=>d.status==='completed').map(d=>d.targetId)]);
 const targets:TargetCandidate[]=[...grouped.entries()].map(([id,x])=>{const best=[...x.pairs].sort((a,b)=>(a.m.fdr+a.t.fdr)-(b.m.fdr+b.t.fdr))[0],reversal=best.m.log2FC*best.t.log2FC<0,cross=x.modules.size,diseaseScore=diseaseMap.get(id)?.associationScore,noveltyScore=undefined,experimental=.32*sig(best.m.fdr)+.32*sig(best.t.fdr)+.18*(reversal?1:0)+.18*clamp((cross-1)/2),score=100*(diseaseScore===undefined?experimental:.8*experimental+.2*clamp(diseaseScore)),bothFdr=best.m.fdr<.05&&best.t.fdr<.05,bothNominal=best.m.pValue<.05&&best.t.pValue<.05,oneFdr=best.m.fdr<.05||best.t.fdr<.05,validated=validatedTargets.has(id),evidenceGrade:EvidenceGrade=validated&&bothFdr&&reversal?'S':bothFdr&&reversal&&cross>1&&diseaseScore!==undefined?'A':bothFdr&&reversal?'B':oneFdr&&bothNominal&&reversal?'C':bothNominal&&reversal?'D':'E',evidenceComponents={modelFdr:best.m.fdr<.05?1:0,treatmentFdr:best.t.fdr<.05?1:0,reversal:reversal?1:0,crossOmics:clamp((cross-1)/2),disease:diseaseScore===undefined?0:clamp(diseaseScore),validation:validated?1:0};return {id,symbol:x.symbol,modules:[...x.modules],modelFdr:best.m.fdr,treatmentFdr:best.t.fdr,modelEffect:best.m.log2FC,treatmentEffect:best.t.log2FC,reversal,crossOmics:cross,diseaseScore,noveltyScore,score,evidenceGrade,evidenceComponents,evidence:[reversal?'模型异常被给药反向调节':'未形成方向逆转',cross>1?`${cross}类组学共同支持`:'单组学支持',bothFdr?'两阶段FDR<0.05':bothNominal?'两阶段P<0.05（探索性）':'统计证据不足',diseaseScore!==undefined?`Open Targets疾病关联${diseaseScore.toFixed(3)}`:'未匹配疾病数据库证据',validated?'已有对接/动力学验证层证据':'尚无结构验证']}}).sort((a,b)=>b.score-a.score);
 const targetMap=new Map(targets.map(x=>[x.symbol.trim().toUpperCase(),x])),compoundMap=new Map(compounds.map(x=>[x.name.trim().toUpperCase(),x])),pairMap=new Map<string,{compoundId:string;compoundName:string;targetId:string;targetSymbol:string;score:number;evidence:string[];dockingAffinity?:number}>();for(const r of chemistry?.data??[]){const name=first(r,['Name','Compound','Compound_Name','化合物','成分名称']).toUpperCase(),c=compoundMap.get(name),raw=first(r,['Target','Targets','Target_Genes','Predicted_Targets','靶点','预测靶点']);if(!c||!raw)continue;for(const symbol of raw.split(/[;,|/]+/).map(x=>x.trim()).filter(Boolean)){const t=targetMap.get(symbol.toUpperCase());if(!t)continue;const key=`${c.id}::${t.id}`;pairMap.set(key,{compoundId:c.id,compoundName:c.name,targetId:t.id,targetSymbol:t.symbol,score:.45*c.score+.45*t.score+10,evidence:['成分原始表靶点注释','本研究活性靶标交集']})}}
 const docking=project.discovery?.docking??[];for(const d of docking){const c=compounds.find(x=>x.id===d.compoundId),t=targets.find(x=>x.id===d.targetId);if(!c||!t||!d.scores.length)continue;const key=`${c.id}::${t.id}`,old=pairMap.get(key),aff=d.scores[0].affinity,bonus=Math.max(0,Math.min(10,-aff));pairMap.set(key,{compoundId:c.id,compoundName:c.name,targetId:t.id,targetSymbol:t.symbol,score:Math.min(100,.45*c.score+.45*t.score+bonus),evidence:[...(old?.evidence??[]),'实际Vina任务结果'],dockingAffinity:aff})}
 const pairs=[...pairMap.values()].sort((a,b)=>b.score-a.score);return {compounds:compounds.sort((a,b)=>b.score-a.score),targets,pairs,diseaseEvidence,docking,md:project.discovery?.md??[],diseaseEvidenceUpdatedAt:project.discovery?.diseaseEvidenceUpdatedAt,warnings:[!chemistry?'未导入实测化学成分':'',!targets.length?'尚无可用于靶标排序的模型—给药成对比较':'',!diseaseEvidence.length?'疾病数据库证据尚未同步时，疾病得分不参与总分':'',!pairs.length?'没有可验证的成分—靶标映射；不会生成全排列伪网络':''].filter(Boolean)};
}
