import type {AnalysisResult,DataAsset,DifferentialRow,ModuleKey,ProjectMeta,Sample,SummaryRow} from './types';
import {bh,finite,mean,quantile,sd,welch} from './stats';import {pca2} from './pca';

const idCandidates=['Gene_ID','gene_id','Gene','gene','Protein_ID','protein_id','Feature_ID','feature_id','Metabolite','Taxon','ASV_ID','id','ID','Name'];
const sampleIdCandidates=['Sample_ID','sample_id','Sample','sample'];
export function runAnalysis(asset:DataAsset,samples:Sample[],meta:ProjectMeta):AnalysisResult{
 const base={id:crypto.randomUUID(),module:asset.module,createdAt:new Date().toISOString(),engineVersion:'TSR-Core-JS 0.2',status:'completed' as const,parameters:{} as Record<string,unknown>,qc:{} as Record<string,unknown>,summaries:[] as SummaryRow[],differential:[] as DifferentialRow[],pca:[],messages:[] as string[]};
 try{const present=new Set(samples.filter(s=>s.included).map(s=>s.group)),missing=[meta.controlGroup,meta.modelGroup].filter(g=>!present.has(g));if(missing.length)throw new Error(`分组映射不完整：数据中未找到 ${missing.join('、')}`);return ['phenotype','scfa'].includes(asset.module)?analyzeIndividual(asset,samples,meta,base):analyzeMatrix(asset,samples,meta,base)}catch(e){return {...base,status:'failed',messages:[e instanceof Error?e.message:'分析失败']}}
}
function analyzeMatrix(asset:DataAsset,samples:Sample[],meta:ProjectMeta,base:AnalysisResult):AnalysisResult{
 const idCol=idCandidates.find(c=>c in (asset.data[0]??{}))??Object.keys(asset.data[0]??{})[0];const included=samples.filter(s=>s.included&&asset.sampleColumns.includes(s.id));if(included.length<4)throw new Error('可匹配且纳入的样本少于4个');
 const raw=asset.data.map(r=>({id:String(r[idCol]),values:Object.fromEntries(included.map(s=>[s.id,Number(r[s.id])]))})).filter(r=>r.id&&Object.values(r.values).some(Number.isFinite));
 const isCounts=asset.module==='transcriptomics'&&raw.flatMap(r=>Object.values(r.values)).filter(Number.isFinite).every(v=>v>=0&&Number.isInteger(v));
 let filtered=raw;if(isCounts)filtered=raw.filter(r=>included.filter(s=>(r.values[s.id]??0)>=10).length>=Math.max(2,Math.floor(included.length*.25)));
 const values=transform(filtered,included,isCounts,asset.module);const summaries:SummaryRow[]=[],diff:DifferentialRow[]=[];
 for(const row of values){const by=groupValues(row.values,included);for(const [g,x] of Object.entries(by))summaries.push(summary(row.id,g,x));const ctl=by[meta.controlGroup]??[],mod=by[meta.modelGroup]??[];if(ctl.length>=2&&mod.length>=2)diff.push(diffRow(row.id,`${meta.modelGroup}_vs_${meta.controlGroup}`,ctl,mod));for(const t of meta.treatmentGroups){const tx=by[t]??[];if(mod.length>=2&&tx.length>=2){const d=diffRow(row.id,`${t}_vs_${meta.modelGroup}`,mod,tx),mc=mean(mod)-mean(ctl);d.recovery=Math.abs(mc)>1e-12?(mean(mod)-mean(tx))/mc:0;diff.push(d)}}}
 applyFdr(diff);const pca=pcaFromFeatures(values,included);return {...base,parameters:{inputScale:isCounts?'raw counts':'quantitative matrix',normalization:isCounts?'CPM + log2(CPM+1)':asset.module==='microbiome'?'relative abundance log2(x+1e-6)':'log2 when all values are positive',lowCountFilter:isCounts?'count≥10 in at least max(2,25% samples)':'not applied',test:'Welch two-sided t-test',fdr:'Benjamini-Hochberg'},qc:{inputFeatures:raw.length,retainedFeatures:filtered.length,matchedSamples:included.length,groups:Object.fromEntries([...new Set(included.map(s=>s.group))].map(g=>[g,included.filter(s=>s.group===g).length])),pcaVariance:pca.variance},summaries,differential:diff,pca:pca.points,messages:filtered.length<raw.length?[`过滤${raw.length-filtered.length}个低表达特征`]:[]}
}
function analyzeIndividual(asset:DataAsset,samples:Sample[],meta:ProjectMeta,base:AnalysisResult):AnalysisResult{
 const sid=sampleIdCandidates.find(c=>c in (asset.data[0]??{}));if(!sid)throw new Error('个体数据需要Sample_ID列');const smap=new Map(samples.filter(s=>s.included).map(s=>[s.id,s]));const rows=asset.data.filter(r=>smap.has(String(r[sid]))),cols=Object.keys(rows[0]??{}).filter(c=>c!==sid&&rows.some(r=>Number.isFinite(Number(r[c]))));if(rows.length<4||!cols.length)throw new Error('未找到足够的配对样本或数值指标');const summaries:SummaryRow[]=[],diff:DifferentialRow[]=[];
 for(const col of cols){const by:Record<string,number[]>={};for(const r of rows){const s=smap.get(String(r[sid]))!,v=Number(r[col]);if(Number.isFinite(v))(by[s.group]??=[]).push(v)}for(const [g,x] of Object.entries(by))summaries.push(summary(col,g,x));const ctl=by[meta.controlGroup]??[],mod=by[meta.modelGroup]??[];if(ctl.length>=2&&mod.length>=2)diff.push(diffRow(col,`${meta.modelGroup}_vs_${meta.controlGroup}`,ctl,mod));for(const t of meta.treatmentGroups){const tx=by[t]??[];if(mod.length>=2&&tx.length>=2){const d=diffRow(col,`${t}_vs_${meta.modelGroup}`,mod,tx),mc=mean(mod)-mean(ctl);d.recovery=Math.abs(mc)>1e-12?(mean(mod)-mean(tx))/mc:0;diff.push(d)}}}applyFdr(diff);return {...base,parameters:{inputScale:'individual measurements',test:'Welch two-sided t-test',fdr:'Benjamini-Hochberg',summary:'mean, SD, median, IQR, range'},qc:{matchedRows:rows.length,numericFeatures:cols.length},summaries,differential:diff,pca:[],messages:[]}
}
function transform(rows:{id:string;values:Record<string,number>}[],samples:Sample[],counts:boolean,module:ModuleKey){if(counts){const libs=Object.fromEntries(samples.map(s=>[s.id,rows.reduce((z,r)=>z+(Number.isFinite(r.values[s.id])?r.values[s.id]:0),0)]));return rows.map(r=>({id:r.id,values:Object.fromEntries(samples.map(s=>[s.id,Math.log2(((r.values[s.id]||0)/(libs[s.id]||1))*1e6+1)]))}))}const all=rows.flatMap(r=>Object.values(r.values)).filter(v=>Number.isFinite(v)),log=all.length>0&&all.every(v=>v>=0)&&(Math.max(...all)>100||module==='microbiome');return rows.map(r=>({id:r.id,values:Object.fromEntries(Object.entries(r.values).map(([k,v])=>[k,Number.isFinite(v)?log?Math.log2(v+(module==='microbiome'?1e-6:1)):v:NaN]))}))}
const groupValues=(v:Record<string,number>,s:Sample[])=>Object.fromEntries([...new Set(s.map(x=>x.group))].map(g=>[g,finite(s.filter(x=>x.group===g).map(x=>v[x.id]))]));
function summary(feature:string,group:string,x:number[]):SummaryRow{return {feature,group,n:x.length,mean:mean(x),sd:sd(x),median:quantile(x,.5),q1:quantile(x,.25),q3:quantile(x,.75),min:Math.min(...x),max:Math.max(...x)}}
function diffRow(featureId:string,comparison:string,a:number[],b:number[]):DifferentialRow{const w=welch(a,b);return {featureId,label:featureId,comparison,meanA:mean(a),meanB:mean(b),log2FC:mean(b)-mean(a),t:w.t,df:w.df,pValue:w.p,fdr:1,effectSize:w.effect,flags:[]}}
function applyFdr(rows:DifferentialRow[]){const groups=[...new Set(rows.map(r=>r.comparison))];for(const c of groups){const sub=rows.filter(r=>r.comparison===c),q=bh(sub.map(r=>r.pValue));sub.forEach((r,i)=>{r.fdr=q[i];if(Math.abs(r.effectSize)>=.8)r.flags.push('large effect');if(r.fdr<.05)r.flags.push('FDR<0.05')})}}
function pcaFromFeatures(rows:{id:string;values:Record<string,number>}[],samples:Sample[]){const ranked=rows.map(r=>({r,v:sd(finite(samples.map(s=>r.values[s.id])))})).sort((a,b)=>b.v-a.v).slice(0,Math.min(500,rows.length)).map(x=>x.r),matrix=samples.map(s=>ranked.map(r=>Number.isFinite(r.values[s.id])?r.values[s.id]:mean(finite(Object.values(r.values))))),p=pca2(matrix);return {variance:p.variance,points:samples.map((s,i)=>({sampleId:s.id,group:s.group,pc1:p.scores[i]?.[0]??0,pc2:p.scores[i]?.[1]??0}))}}
