import {useMemo,useState} from 'react';import {buildDiscovery} from './discovery';import type {DiscoveryState,DiseaseTargetEvidence,DockingRun,MDRun,Project} from './types';

export function PipelineV07({project,save}:{project:Project;save:(x:DiscoveryState)=>void}){
 const discovery=useMemo(()=>buildDiscovery(project),[project]),[runtime,setRuntime]=useState<Record<string,unknown>|null>(null),[notice,setNotice]=useState('');
 const [compoundId,setCompound]=useState(''),[targetId,setTarget]=useState(''),[receptor,setReceptor]=useState(''),[ligand,setLigand]=useState(''),[topology,setTopology]=useState(''),[trajectory,setTrajectory]=useState(''),[group,setGroup]=useState(1),[threads,setThreads]=useState(2),[gpu,setGpu]=useState(true),[box,setBox]=useState({centerX:0,centerY:0,centerZ:0,sizeX:22,sizeY:22,sizeZ:22,exhaustiveness:16,numModes:9,seed:20260713});
 const compounds=discovery.compounds,targets=discovery.targets,cid=compoundId||compounds[0]?.id||'',tid=targetId||targets[0]?.id||'';
 async function check(){setRuntime(window.tsrDesktop?await window.tsrDesktop.checkRuntime():{提示:'浏览器预览不能调用本机Vina/GROMACS'})}
 async function resolveCompounds(){if(!window.tsrDesktop)return setNotice('在线身份匹配仅在桌面版运行');const out=[...compounds];let ok=0;for(let i=0;i<out.length;i++){const c=out[i];if(c.pubchemCid&&c.smiles)continue;setNotice(`正在查询PubChem：${i+1}/${out.length} ${c.name}`);const r=await window.tsrDesktop.resolveCompound(c);if(!r.ok)continue;const x=r.result as {name?:string;pubchemCid?:string;smiles?:string};out[i]={...c,pubchemCid:x.pubchemCid||c.pubchemCid,smiles:x.smiles||c.smiles,identityLevel:`${c.identityLevel}；PubChem自动匹配`,flags:c.flags.filter(f=>!f.includes('缺少CAS')),score:Math.max(c.score,65)};ok++}save({...discovery,compounds:out});setNotice(`PubChem匹配完成：补全${ok}条；未匹配记录保留原样并需人工复核`)}
 async function syncDisease(){if(!window.tsrDesktop)return setNotice('疾病证据同步仅在桌面版运行');setNotice(`正在查询Open Targets：${project.meta.disease}`);const r=await window.tsrDesktop.resolveDiseaseTargets(project.meta.disease);if(!r.ok)return setNotice(r.error??'疾病证据查询失败');const x=r.result as {targets:DiseaseTargetEvidence[];queriedAt:string;disease:{id:string;name:string}};save({...discovery,diseaseEvidence:x.targets,diseaseEvidenceUpdatedAt:x.queriedAt});setNotice(`已同步${x.disease.name}的${x.targets.length}条靶标关联；仅与本研究候选交叉加权`)}
 async function pick(kind:'receptor'|'ligand'|'topology'|'trajectory',setter:(x:string)=>void){const x=await window.tsrDesktop?.selectStructure(kind);if(x)setter(x)}
 async function dock(){if(!window.tsrDesktop)return setNotice('分子对接只能在桌面版运行');setNotice('Vina正在运行…');const r=await window.tsrDesktop.runDocking({compoundId:cid,targetId:tid,receptor,ligand,...box});if(!r.ok)return setNotice(r.error??'对接失败');save({...discovery,docking:[...discovery.docking,r.result as DockingRun]});setNotice('对接完成，构象、评分和参数已写入项目')}
 async function md(){if(!window.tsrDesktop)return setNotice('动力学分析只能在桌面版运行');setNotice('GROMACS正在解析轨迹…');const r=await window.tsrDesktop.runMD({compoundId:cid,targetId:tid,topology,trajectory,group});if(!r.ok)return setNotice(r.error??'动力学分析失败');save({...discovery,md:[...discovery.md,r.result as MDRun]});setNotice('RMSD/RMSF/Rg/SASA/氢键结果已写入项目')}
 async function runProduction(){if(!window.tsrDesktop)return setNotice('生产模拟只能在桌面版运行');setNotice('GROMACS生产模拟正在运行；存在检查点时自动续算…');const r=await window.tsrDesktop.runMDProduction({topology,threads,gpu,name:`${cid}_${tid}`});if(!r.ok)return setNotice(r.error??'生产模拟失败');const x=r.result as {trajectory:string;topology:string;resumed:boolean};setTrajectory(x.trajectory);setTopology(x.topology);setNotice(`生产模拟完成${x.resumed?'（由检查点续算）':''}；可继续解析轨迹`)}
 const stages=[['实测活性成分',compounds.length,compounds.some(x=>x.smiles||x.pubchemCid||x.cas)?'已识别身份':'等待CAS/CID/SMILES'],['活性靶标',targets.length,targets.length?'已生成透明评分':'等待成对组学结果'],['分子对接',discovery.docking.length,runtime?'运行时已检测':'待检测Vina'],['分子动力学',discovery.md.length,runtime?'运行时已检测':'待检测GROMACS']];
 return <><section><div className="sectionHead"><div><h2>发现—验证全过程</h2><p>实测成分、多组学逆转、疾病证据、对接和动力学分层保存；缺失环节不会自动补造。</p></div><div><button onClick={resolveCompounds}>匹配PubChem身份</button><button onClick={syncDisease}>同步疾病靶点</button><button onClick={check}>检测R / Vina / GROMACS</button></div></div>{notice&&<div className="notice">{notice}</div>}{runtime&&<div className="qc warning"><b>本机运行时</b><span>{JSON.stringify(runtime)}</span></div>}<div className="cards">{stages.map(([n,v,s])=><article key={String(n)}><b>{v}</b><span>{n}<br/>{s}</span></article>)}</div>{discovery.warnings.map(x=><div className="qc warning" key={x}><b>限制</b><span>{x}</span></div>)}</section>
 <section><h2>候选成分与活性靶标</h2><p className="muted">成分评分：身份可追溯性65%＋实测暴露/丰度35%。靶标评分：模型异常32%＋给药恢复32%＋方向逆转18%＋跨组学一致18%；疾病证据未同步时不参与。</p><h3>成分 Top 20</h3><table><thead><tr><th>成分</th><th>CAS</th><th>PubChem CID</th><th>SMILES</th><th>身份等级</th><th>评分</th><th>提示</th></tr></thead><tbody>{compounds.slice(0,20).map(x=><tr key={x.id}><td>{x.name}</td><td>{x.cas||'—'}</td><td>{x.pubchemCid||'—'}</td><td className="clip">{x.smiles||'—'}</td><td>{x.identityLevel}</td><td>{x.score.toFixed(1)}</td><td>{x.flags.join('；')||'—'}</td></tr>)}</tbody></table><h3>靶标 Top 30</h3><table><thead><tr><th>靶标</th><th>组学</th><th>模型FDR</th><th>给药FDR</th><th>模型效应</th><th>给药效应</th><th>逆转</th><th>评分</th></tr></thead><tbody>{targets.slice(0,30).map(x=><tr key={x.id}><td>{x.symbol}</td><td>{x.modules.join(';')}</td><td>{fmt(x.modelFdr)}</td><td>{fmt(x.treatmentFdr)}</td><td>{fmt(x.modelEffect)}</td><td>{fmt(x.treatmentEffect)}</td><td>{x.reversal?'是':'否'}</td><td>{x.score.toFixed(1)}</td></tr>)}</tbody></table><h3>有证据的成分—靶标对</h3><table><thead><tr><th>成分</th><th>靶标</th><th>联合评分</th><th>对接亲和力</th><th>建边依据</th></tr></thead><tbody>{discovery.pairs.slice(0,50).map(x=><tr key={`${x.compoundId}-${x.targetId}`}><td>{x.compoundName}</td><td>{x.targetSymbol}</td><td>{x.score.toFixed(1)}</td><td>{x.dockingAffinity??'—'}</td><td>{x.evidence.join('；')}</td></tr>)}</tbody></table></section>
 <section><h2>AutoDock Vina 单对验证</h2><p className="muted">先验证口袋和参数，再扩展批量任务。对接分数仅作候选优先级，不证明真实结合。</p><div className="form form2"><Select label="成分" value={cid} set={setCompound} items={compounds.map(x=>[x.id,x.name])}/><Select label="靶标" value={tid} set={setTarget} items={targets.map(x=>[x.id,x.symbol])}/><Path label="受体PDBQT" value={receptor} pick={()=>pick('receptor',setReceptor)}/><Path label="配体PDBQT" value={ligand} pick={()=>pick('ligand',setLigand)}/>{Object.entries(box).map(([k,v])=><label key={k}>{k}<input type="number" value={v} onChange={e=>setBox({...box,[k]:Number(e.target.value)})}/></label>)}</div><button className="primary" disabled={!cid||!tid||!receptor||!ligand} onClick={dock}>运行并保存对接</button>{discovery.docking.length>0&&<table><thead><tr><th>成分</th><th>靶标</th><th>最佳亲和力</th><th>构象数</th><th>输出</th><th>时间</th></tr></thead><tbody>{discovery.docking.map(x=><tr key={x.id}><td>{x.compoundId}</td><td>{x.targetId}</td><td>{x.scores[0]?.affinity??'未解析'}</td><td>{x.scores.length}</td><td>{x.poseFile}</td><td>{x.createdAt}</td></tr>)}</tbody></table>}</section>
 <section><h2>GROMACS 生产模拟与轨迹分析</h2><p className="muted">使用已审查的TPR执行生产期模拟，检测同名CPT后自动断点续算；随后生成RMSD、RMSF、回转半径、SASA和氢键时间序列。默认组编号1通常为Protein，请按TPR分组修改。</p><div className="form form2"><Path label="拓扑TPR" value={topology} pick={()=>pick('topology',setTopology)}/><Path label="已有轨迹XTC/TRR" value={trajectory} pick={()=>pick('trajectory',setTrajectory)}/><label>CPU线程<input type="number" min="1" value={threads} onChange={e=>setThreads(Number(e.target.value))}/></label><label>GPU加速<select value={gpu?'yes':'no'} onChange={e=>setGpu(e.target.value==='yes')}><option value="yes">自动使用GPU</option><option value="no">仅CPU</option></select></label><label>分析组编号<input type="number" min="0" value={group} onChange={e=>setGroup(Number(e.target.value))}/></label></div><button disabled={!cid||!tid||!topology} onClick={runProduction}>运行/续算生产期</button> <button className="primary" disabled={!cid||!tid||!topology||!trajectory} onClick={md}>解析轨迹并保存结果</button>{discovery.md.map(x=><div className="qc ready" key={x.id}><b>{x.compoundId}—{x.targetId}</b><span>{x.series.map(s=>`${s.name}:${s.points.length}点`).join('；')}</span></div>)}</section></>
}
function Select({label,value,set,items}:{label:string;value:string;set:(x:string)=>void;items:string[][]}){return <label>{label}<select value={value} onChange={e=>set(e.target.value)}>{items.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>}
function Path({label,value,pick}:{label:string;value:string;pick:()=>void}){return <label>{label}<div className="pathPick"><input value={value} readOnly/><button type="button" onClick={pick}>选择</button></div></label>}
const fmt=(x:number)=>Number.isFinite(x)?(Math.abs(x)<.001?x.toExponential(2):x.toFixed(3)):'—';
