import {buildDiscovery} from './discovery';import type {Project} from './types';
export type GateLevel='pass'|'warning'|'block';export interface GateItem{id:string;area:string;level:GateLevel;message:string;requirement:string}
export function publicationGate(p:Project){const items:GateItem[]=[],included=p.samples.filter(s=>s.included),groups=[p.meta.controlGroup,p.meta.modelGroup,...p.meta.treatmentGroups].filter(Boolean),counts=new Map(groups.map(g=>[g,included.filter(s=>s.group===g).length]));
 add(items,'design','研究设计',p.meta.name&&p.meta.disease&&p.meta.controlGroup&&p.meta.modelGroup?'pass':'block','项目、疾病、空白组和模型组完整','必须记录预设研究设计');
 add(items,'replicates','生物学重复',[...counts.values()].every(n=>n>=3)?'pass':'block',groups.map(g=>`${g}:${counts.get(g)??0}`).join('；'),'每个核心组至少3个独立生物学重复；正式功效仍需功效分析');
 add(items,'sample_ids','样本追溯',new Set(included.map(s=>s.id)).size===included.length&&included.every(s=>s.animalId)?'pass':'block','Sample ID唯一且Animal ID完整','跨文件必须使用稳定样本与动物标识');
 add(items,'qc','数据质控',p.assets.some(a=>a.status==='blocked')?'block':p.assets.some(a=>a.status==='warning')?'warning':'pass',p.assets.map(a=>`${a.module}:${a.status}`).join('；')||'未导入数据','阻断数据不得进入正式结果');
 const tx=p.results.find(r=>r.module==='transcriptomics'),pr=p.results.find(r=>r.module==='proteomics');if(p.assets.some(a=>a.module==='transcriptomics'))add(items,'tx_model','转录组模型',tx?.engineVersion.includes('DESeq2')?'pass':'block',tx?.engineVersion??'未运行','raw counts必须使用DESeq2/edgeR类计数模型');if(p.assets.some(a=>a.module==='proteomics'))add(items,'protein_model','蛋白组模型',pr?.engineVersion.toLowerCase().includes('limma')?'pass':'block',pr?.engineVersion??'未运行','蛋白组正式结果使用limma/MSstats类模型');
 if(p.assets.some(a=>a.module==='metabolomics'))add(items,'metabolomics_model','代谢组正式流程','warning','当前完成矩阵统计；需核对QC样本、漂移、批次及注释等级','正式发表必须报告QC-RLSC/批次处理、缺失机制及代谢物鉴定置信度');if(p.assets.some(a=>a.module==='microbiome'))add(items,'microbiome_model','菌群组成型统计','block','当前通用矩阵结果不能作为正式菌群差异结论','正式发表必须使用ANCOM-BC/ALDEx2等组成型方法并报告测序深度与过滤');
 const unrun=p.assets.filter(a=>!['chemistry'].includes(a.module)&&!p.results.some(r=>r.module===a.module&&r.status!=='failed'));add(items,'analysis_complete','分析完整性',unrun.length?'block':'pass',unrun.length?`未完成：${unrun.map(x=>x.module).join('、')}`:'已导入模块均有结果','导入的数据必须完成或明确排除');
 const d=buildDiscovery(p),identified=d.compounds.filter(x=>x.cas||x.pubchemCid||x.smiles).length;add(items,'compound_identity','成分身份',!d.compounds.length?'warning':identified===d.compounds.length?'pass':'warning',`${identified}/${d.compounds.length}具有CAS/CID/SMILES`,'重点成分必须具有可追溯身份及鉴定等级');add(items,'disease_evidence','疾病证据',d.diseaseEvidence.length&&d.diseaseEvidenceUpdatedAt?'pass':'warning',d.diseaseEvidenceUpdatedAt??'未同步','外部数据库必须记录来源与查询日期');
 add(items,'target_evidence','活性靶标',d.targets.some(x=>x.reversal&&x.modelFdr<.05&&x.treatmentFdr<.05)?'pass':'warning',`${d.targets.length}个候选，严格双阶段逆转${d.targets.filter(x=>x.reversal&&x.modelFdr<.05&&x.treatmentFdr<.05).length}个`,'严格候选优先要求模型与给药两阶段FDR及方向逆转');add(items,'structure','结构验证',d.docking.length&&d.md.length?'pass':'warning',`对接${d.docking.length}次；动力学${d.md.length}次`,'仅在论文提出直接结合或结构稳定性结论时为必需');
 add(items,'audit','可重复性',p.results.every(r=>r.createdAt&&r.engineVersion&&Object.keys(r.parameters).length)?'pass':'block','分析引擎、时间和参数记录','所有结果必须带软件、参数和时间戳');const blocks=items.filter(x=>x.level==='block').length,warnings=items.filter(x=>x.level==='warning').length,passes=items.filter(x=>x.level==='pass').length;return {status:blocks?'blocked':warnings?'conditional':'ready',score:Math.round(100*(passes+.5*warnings)/items.length),blocks,warnings,passes,generatedAt:new Date().toISOString(),items}}
function add(a:GateItem[],id:string,area:string,level:GateLevel,message:string,requirement:string){a.push({id,area,level,message,requirement})}
