import type {Project} from './types';import {publicationGate} from './publication';
export function exportResearchReport(project:Project){const lines=[`# ${project.meta.name}：TSR Studio 3.0.2研究分析报告`,'',`生成时间：${new Date().toISOString()}`,`疾病/模型：${project.meta.disease}`,`物种：${project.meta.species}`,'',readiness(project),'',design(project),'',methods(project),'',results(project),'',limitations(project),'',audit(project)];download(new Blob([lines.join('\n')],{type:'text/markdown;charset=utf-8'}),`${safe(project.meta.name)}_TSR_Studio_3.0.2_Report.md`)}
function readiness(p:Project){const g=publicationGate(p);return `## 发表就绪检查\n\n- 状态：${g.status}\n- 评分：${g.score}/100\n- 阻断：${g.blocks}项；警告：${g.warnings}项\n\n${g.items.map(x=>`- [${x.level}] ${x.area}：${x.message}（要求：${x.requirement}）`).join('\n')}\n\n此检查表示分析记录完整性，不代表期刊接收或因果结论成立。`}
function design(p:Project){return `## 研究设计\n\n- 空白组：${p.meta.controlGroup}\n- 模型组：${p.meta.modelGroup}\n- 给药组：${p.meta.treatmentGroups.join('、')||'未设置'}\n- 纳入样本：${p.samples.filter(s=>s.included).length}\n- Animal ID数：${new Set(p.samples.filter(s=>s.included).map(s=>s.animalId)).size}`}
function methods(p:Project){const mods=p.results.map(r=>`### ${r.module}\n\n- 引擎：${r.engineVersion}\n- 参数：${JSON.stringify(r.parameters)}\n- QC：${JSON.stringify(r.qc)}\n- 多重校正：按比较进行Benjamini–Hochberg FDR\n- 证据分层：FDR<0.05为严格显著；P<0.05但FDR未通过为探索性候选。`).join('\n\n');return `## 方法\n\n${mods||'尚未运行分析。'}`}
function results(p:Project){return `## 结果概览\n\n${p.results.map(r=>{const strict=r.differential.filter(d=>d.fdr<.05),nom=r.differential.filter(d=>d.pValue<.05&&d.fdr>=.05),top=[...r.differential].sort((a,b)=>a.fdr-b.fdr||a.pValue-b.pValue).slice(0,15);return `### ${r.module}\n\n- 全部比较结果：${r.differential.length}\n- FDR严格显著：${strict.length}\n- P值探索候选：${nom.length}\n- PCA样本点：${r.pca.length}\n\n|特征|比较|变化|P值|FDR|\n|---|---|---:|---:|---:|\n${top.map(d=>`|${d.label||d.featureId}|${d.comparison}|${d.log2FC.toPrecision(4)}|${d.pValue.toExponential(3)}|${d.fdr.toExponential(3)}|`).join('\n')}`}).join('\n\n')}`}
function limitations(p:Project){const x=[];if(!p.results.some(r=>r.module==='transcriptomics'))x.push('未提供或未完成转录组，不进行TF—mRNA推断');if(!p.results.some(r=>r.module==='metabolomics'))x.push('未提供或未完成代谢组，不构造代谢物—酶反应层');if(!p.results.some(r=>r.module==='microbiome'))x.push('未提供或未完成菌群数据');if(!p.results.some(r=>r.module==='scfa'))x.push('未提供或未完成SCFA数据');if(new Set(p.samples.map(s=>s.animalId)).size===p.samples.length)x.push('尚无跨文件复用的Animal ID，不进行逐动物跨组学相关');if(!p.discovery?.diseaseEvidence?.length)x.push('尚未同步疾病靶点证据');if(!p.discovery?.docking?.length)x.push('尚无实际分子对接运行结果');if(!p.discovery?.md?.length)x.push('尚无实际分子动力学轨迹分析结果');return `## 限制\n\n${x.map(v=>`- ${v}`).join('\n')||'- 未检测到结构性缺失；仍需独立实验验证。'}\n- 对接评分和动力学稳定性不等于体内靶标确证。\n- 自动报告不替代统计人员复核。\n- 网络关系表示候选证据链，不证明因果。`}
function audit(p:Project){return `## 可重复性与审计\n\n- 项目格式：${p.schema}\n- 创建时间：${p.createdAt}\n- 最后更新时间：${p.updatedAt}\n- 数据文件：${p.assets.map(a=>`${a.module}: ${a.fileName} (${a.rows}×${a.columns}, ${a.sourceFormat??'table'})`).join('；')}\n- 每张论文图的SVG、PNG、源数据和图注应从同一项目状态导出。`}
function download(b:Blob,n:string){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}const safe=(s:string)=>s.replace(/[^A-Za-z0-9\u4e00-\u9fa5_.-]+/g,'_');
